### ISSUE TITLE
Add Provider without API Key and change Content Type Request

### ISSUE THREAD

**Issue by SylvesterAT** [JonasJoKuJonas/homeassistant-trias#1]
Hej Jonas,

I am super happy that I found your Home Assistant integration. Unfortunately, I was not able to add the Provider "Verbundlinie Steiermark/Verkehrsverbund Steiermark". They use a public API without an API Key and they told me that the content-type must be "text/xml" for every request sent via the API. How can I changes this in your integration?

Best,
Sylvester.

**Comment by JonasJoKuJonas** [comment]
Which URL do I need to use to test it?

**Comment by SylvesterAT** [comment]
Hej Jonas,
thank you for your reply. Can I share the link with you via E-Mail? According to the provider it is confidential.
Thank you!
Best,Peter

**Comment by JonasJoKuJonas** [comment]
Thank you for sharing the Link. I now implemented the login without an API key and fixed some bugs with this API.
Let me know if it works for you.

And thanks for supporting this project ;)

**Comment by SylvesterAT** [comment]
Thank you for the update and your great support! Adding the linked and searching for stops works perfectly. 

Unfortunately when I try to add a stop, I only get an Error message: „Error setting up entry Name of the device for trias“
